name: createArtifact

on: push

env:
  ARTIFACT_NAME: myArtifact01

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: ./${{ env.ARTIFACT_NAME }}
