name: create-artifact

on: push

env:
  ARTIFACT_NAME: my-artifact

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
